export enum TableCellTypeEnum {
  TEXT = 'text',
  IMAGE = 'image',
  DATE = 'date',
  CHECKBOX = 'checkbox',
  CHECKBOX2 = 'checkbox2',
  SLIDE_TOGGLE = 'slide_toggle',
  LINK = 'link',
  TRUE_FALSE = 'true_false',
  FEEDBACK = 'feedback',
  STARS = 'stars',
  FLAG = 'flag',
  ACTIONS = 'actions',
  ARRAY = 'array',
  SEVERITY = 'severity',
  CONFIDENCE = 'confidence',
  DEVIANCE = 'deviance',
  COUNT = 'count',
  HTML = 'html',
  ICONB64 = 'iconb64',
  ICON = "icon",
  PROGRESS = 'progress',
}
