const commonColumns = {
    ipDetails: [
      '@timestamp',
      'src_ip',
      'src_port',
      'dest_ip',
      'dest_port',
      'startDate',
      'endDate',
    ],
    geoIpColumns: [
      "src_geoip.geo.country_iso_code",
      "dest_geoip.geo.country_iso_code",
    ]
  };
  
  export const columnSets = {
    overview: {
      displayed: [
        ...commonColumns.ipDetails,
        'alert.signature',
        'threat',
        'alert.severity',
        'alert.rev',
        'app_proto'
      ],
      requested: [
        ...commonColumns.ipDetails,
        ...commonColumns.geoIpColumns,
        'alert.signature',
        'alert.signature_id',
        'threat',
        'alert.severity',
        'proto',
        'app_proto',
        'mitre_techniques',
      ],
    },
    dns: {
      displayed: [
        ...commonColumns.ipDetails,
        'query', //'dns.rrname',
        'answers',
        'qtype_name', //'dns.rrtype',
      ],
      requested: [
        ...commonColumns.ipDetails,
        ...commonColumns.geoIpColumns,
        'community_id',
        'uid',
        'proto',
        'trans_id',
        'rtt',
        'query',
        'qclass',
        'qclass_name',
        'qtype',
        'qtype_name',
        'rcode',
        'rcode_name',
        'AA',
        'TC',
        'RD',
        'RA',
        'Z',
        'answers',
        'TTLs',
        'rejected'
      ],
    },
    fileInfo: {
      displayed: [
        ...commonColumns.ipDetails,
        'fileinfo.filename',
        'fileinfo.size',
        'fileinfo.stored',
        'fileinfo.state',
        'http.hostname',
        'http.url',
        'http.http_method',
        'http.status',
        'app_proto',
      ],
      requested: [
        ...commonColumns.ipDetails,
        ...commonColumns.geoIpColumns,
        'fileinfo.filename',
        'fileinfo.size',
        'fileinfo.stored',
        'fileinfo.md5',
        'app_proto',
        'proto',
        'fileinfo.sha256',
        'fileinfo.state',
        'fileinfo.gaps',
        'fileinfo.tx_id',
        'http.hostname',
        'http.url',
        'http.http_method',
        'http.status',
        'http.http_content_type',
        'http.http_refer',
        'http.http_user_agent',
        'http.user_agent.name',
        'http.user_agent.os.full',
        'http.user_agent.os.version',
        'http.user_agent.device.name',
        'http.user_agent.version',
        'http.length',
      ],
    },
    http: {
      displayed: [
        ...commonColumns.ipDetails,
        'http.http_method',
        'http.hostname',
        'http.url',
      ],
      requested: [
        ...commonColumns.ipDetails,
        ...commonColumns.geoIpColumns,
        'http.http_method',
        'http.hostname',
        'http.url',
        'http.protocol',
        'proto',
        'http.http_content_type',
        'http.http_refer',
        'http.http_user_agent',
        'http.user_agent.os.full',
        'http.user_agent.name',
        'http.user_agent.version',
        'http.status',
        'http.user_agent.device.name',
      ],
    },
    krb5: {
      displayed: [
        ...commonColumns.ipDetails,
        'krb5.cname',
        'krb5.realm',
        'krb5.sname',
      ],
      requested: [
        ...commonColumns.ipDetails,
        ...commonColumns.geoIpColumns,
        'krb5.cname',
        'krb5.realm',
        'krb5.sname',
        'krb5.msg_type',
        'krb5.encryption',
        'krb5.weak_encryption',
        'proto',
      ],
    },
    rdp: {
      displayed: [
        ...commonColumns.ipDetails,
        'rdp.event_type',
        'rdp.cookie',
        'rdp.tx_id',
      ],
      requested: [
        ...commonColumns.ipDetails,
        ...commonColumns.geoIpColumns,
        'rdp.event_type',
        'rdp.cookie',
        'rdp.tx_id',
        'proto',
        'community_id',
        'flow_id',
      ],
    },
    smb: {
      displayed: [...commonColumns.ipDetails, 'smb.command'],
      requested: [
        ...commonColumns.ipDetails,
        ...commonColumns.geoIpColumns,
        'smb.command',
        'smb.client_dialects',
        'smb.client_guid',
        'smb.dialect',
        'smb.session_id',
        'smb.tree_id',
        'smb.server_guid',
        'proto',
      ],
    },
    ssh: {
      displayed: [
         ...commonColumns.ipDetails,
        'client',
        'server',
        'auth_attempts',
        'auth_success',
      ],
      requested: [
        //  ...commonColumns.ipDetailsSSh,
         ...commonColumns.ipDetails,
        ...commonColumns.geoIpColumns,
        'uid',
        'version',
        'proto',
        'auth_success',
        'auth_attempts',
        'client',
        'server',
        'cipher_alg',
        'mac_alg',
        'compression_alg',
        'kex_alg',
        'host_key_alg',
        'host_key',
        'hasshVersion',
        'hassh',
        'hasshServer',
        'cshka',
        'proto',
        'hasshAlgorithms',
        'hasshServerAlgorithms',
      ],
    },
    tls: {
      displayed: [...commonColumns.ipDetails, 'version'],
      requested: [
        ...commonColumns.ipDetails,
        ...commonColumns.geoIpColumns,
        'version',
        'cipher',
        'proto',
        'curve',
        'ja3',
        'ja3s',
        'proto',
        'cert_chain_fps',
        'client_cert_chain_fps',
        'validation_status',
        'established',
        'resumed',
        'client_version',
        'server_version',
        'client_ciphers',
        'client_supported_versions',
        'client_key_share_groups',
        'client_curves',
        'client_comp_methods',
        'ssl_client_exts',
        'ssl_server_exts',
        'psk_key_exchange_modes',
        'sigalgs',
        'hashalgs',
        'ssl_history',
        'next_protocol',
        'orig_alpn',
        'valid_ct_logs',
        'valid_ct_operators',
      ],
    },
  };